MONGODB_HOST: mongodb-{{ env }}.surekhadevops.biz # mongodb-dev.surekhadevops.biz
REDIS_HOST: redis-{{ env }}.surekhadevops.biz
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.surekhadevops.biz
CART_HOST: cart.backend-alb-{{ env }}.surekhadevops.biz
USER_HOST: user.backend-alb-{{ env }}.surekhadevops.biz
RABBITMQ_HOST: rabbitmq-{{ env }}.surekhadevops.biz
MYSQL_HOST: mysql-{{ env }}.surekhadevops.biz
SHIPPING_HOST: shipping.backend-alb-{{ env }}.surekhadevops.biz
PAYMENT_HOST: payment.backend-alb-{{ env }}.surekhadevops.biz